### ISSUE TITLE
Display overlaps when changing menus

### ISSUE THREAD

**Issue by victorcampeanu** [EdNekebno/DGTCentaur#101]
building the **_dev_** branch has the menus overlapping when changing between them.

![image](https://user-images.githubusercontent.com/1705918/148655399-b4d11c21-ff20-46a4-87bb-9773e6ddaea8.png)

**Comment by wormstein** [comment]
Valid. I could reproduce this. Seems like screen is not cleared fast enough before the new image is drawn.

**Comment by wormstein** [comment]
Note: Dev branch is not very different than master at this point. The only change is is in menu.py to close serial port before starting centaur software. He is running Bullseye.
