### ISSUE TITLE
Board events

### ISSUE THREAD

**Issue by wormstein** [EdNekebno/DGTCentaur#2]
Hi,
first of alll, this is not an issue but since discussions tab is not open for this project I put this here,

You work is great and opens a lot of possibilities to improve this board. I was trying myself to sniff serial comm but just coudn't find a software way to do it, I guess you are using a hardware reader.

Anyway, my question is if you figured out the coding for the following board events:
- pievce off position (board beeps and highlights square rapidly)
- piece to wrong position (board beeps and highlights both correct and wrong square)
- move (after a piece move, board highlights new position)
- new game: not sure if this is hardware detected but I guess board detects all pieces in place and signal the software to reset.

Cheers,
Adrian

**Comment by EdNekebno** [comment]
I used strace on the centaur process, and then python injected into that process to force circumstances where I could read out the data. That centaur process exposes a number of basic functions - so I just did the ones I needed at the time.

Of your things - the second is in the boardfunctions.py (beep,ledFromTo) - it's not a hardware features - the centaur process calculates it. 

- I don't think there's a board feature to flash rapidly - so I suspect that the centaur process just calls led() and ledsOff() rapidly.
- There is a board function for led() that highlights a single led. But I didn't pull it out as I haven't yet needed it.
- I suspect there is a message from the board to the software when all the pieces are in their starting position. I haven't tested for it or look for the message yet.

**Comment by wormstein** [comment]
Tks for quick reply.

I was playing the strace way but trying to get read-write calls of the process just returns silence while board events are triggered. Any idea what I am missing here?

I also noticed there is a way for the board to query a squares if there is or not a piece sitting there, You can see this happening at the beginning when you are setting the pieces fot a new game, board will trigger a new game event but if you don't have all pieces in place the boatd knows and highlights the square.

To bad the board only knows about pieces and not what kind are they...

If you publish what other events codes you have but didn't implemented, I could try to contribute.

-Adrian

**Comment by EdNekebno** [comment]
I didn't get the codes for anything I didn't implement. The only function I wrote down that is in the centaur program that I didn't implement is led(x) - which just lights one square. Most of the working out what is happening is actually in the centaur software - not the hardware - the hardware seems to do the absolute minimum possible. I suspect when you start a new game it can only check that the ranks 1,2,7 + 8 are full. There wasn't anything I saw that would get the board state (as in the squares that had pieces) - the centaur process has to remember it. Though that would be really useful!

I have no charge in my DGT centaur at the moment...in about half an hour to an hour I'll have my extension cord back from my 3d printer :) Then I'll try and take a look and remember what I did. If nothing else it would be good to get the single led function working.

**Comment by EdNekebno** [comment]
I take it back...there are some possible candidates for flashing leds and starting games:

>>> dir(__main__.serial)
['LEDS_DOUBLE_SPEED', 'LEDS_SINGLE_SPEED', 'LEDS_STYLE', 'SOUND_FACTORY', 'SOUND_GENERAL', 'SOUND_POWER_OFF', 'SOUND_POWER_ON', 'SOUND_WRONG', 'SOUND_WRONG_MOVE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'allowOff', 'batteryReady', 'beep', 'board_change_empty', 'board_change_four_rows', 'bus_add_h', 'bus_add_l', 'buttonCommand', 'calibrationFilter', 'changesCommand', 'check_firmware', 'check_sum', 'closeSerialPort', 'disableOff', 'disable_off_one_time', 'doCommand', 'doCommandWithData', 'doHold', 'doLEDs', 'doOff', 'doPing', 'doRecalibrate', 'doResponse', 'doSendCalVal', 'doSendStats', 'doSendStrength', 'doShutDown', 'doSound', 'enableKeys', 'factoryDetected', 'factoryNotify', 'fieldUpdate', 'firmwareCheck', 'ignoredCount', 'ignoredKey', 'initSerialPort', 'keyHold', 'keyHoldTime', 'lastBattery', 'lastButtonState', 'led', 'ledFromTo', 'led_data', 'led_flash', 'led_shutdown_sequence', 'leds', 'ledsOff', 'level_dim', 'lightLevel', 'lock', 'log_debug', 'measureBatt', 'measure_battery', 'msgIndex', 'offKeyDown', 'offTime', 'openSerialPort', 'playKeyStartup', 'play_sound', 'port', 'processLogMessage', 'readByte', 'readStartByte', 'ready', 'recalibrate', 'recalibrate_board', 'rotateField', 'rotated', 'running', 'sendBoard', 'sendCalVal', 'sendStats', 'sendStrength', 'send_board', 'send_calval', 'send_command', 'send_stats', 'send_strength', 'serialReady', 'serialThread', 'set_startup_mode', 'shut_down', 'shutdown', 'sound', 'start', 'startGame', 'start_game', 'startupMode', 'statisticsFilter', 'stop', 'swapField', 'thread', 'timeout', 'version']

**Comment by EdNekebno** [comment]
Strace command I've been using is something like: strace -p <processnum> -f -e trace=write -y -xx

In boardfunctions.py I've added leds(num) and ledFlash()

I tweeted a quick video that shows the process: https://twitter.com/ednekebno/status/1426991968903700483  (you might need to pause and put up with twitter video quality but it should give the idea)

**Comment by wormstein** [comment]
Thabks for pushing the updates.

I will close this "issue" and have any other conversation in the discussions tab.

Cheerrs,
Adrian
