### ISSUE TITLE
Pre-alpha release issues

### ISSUE THREAD

**Issue by wormstein** [EdNekebno/DGTCentaur#82]
Unfortunately most things are broken when you install it on latest raspbian and put it in the board :( I've made the following changes on my sdcard to make it work (I think....mostly):

DGTCentaurMods.service - won't start as python3.9 is in bullseye, not 3.7 - modified python3.7 command line in the file to python3
Nothing could write to the fen.log and would error out - chown pi /home/pi/centaur; chgrp pi /home/pi/centaur
For bluetooth:
added PyBluez==0.23.0 and psutil==5.8.0 to requirements.txt and pip3 install -r requirements.txt
apt install libbluetooth-dev
apt install bluez-tools
Modified bluetooth.service:
ExecStart=/usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap,battery
ExecStartPost=/usr/bin/sdptool add SP
Also in dbus-org.bluez.service:
ExecStart=/usr/libexec/bluetooth/bluetoothd --compat --noplugin=sap,battery
ExecStartPost=/usr/bin/sdptool add SP
(I suspect modifying the bluetooth.service is unnecessary, it seemed to be the second one that worked but I just did both. It's possible this was installed by the apt install commands)
In /etc/bluetooth/main.conf
Uncommented:
DiscoverableTimeout = 0
PairableTimeout = 0
Added:
JustWorksRepairing=always

For problems finding the python module when I was testing I did this again: cd /usr/lib/python3/dist-packages; ln -s /home/pi/DGTCentaurMods DGTCentaurMods

If I can find somewhere to put it, I can probably also take my wifi key out and image this sd-card.

**Comment by wormstein** [comment]
0.1.1 should be out by sunday

**Comment by cyberluke** [comment]
Hi, any news on this? What is the last working Raspbian release?

**Comment by wormstein** [comment]
Hi. this pre-alpha release is the only one we did and was supposed to work on Buster. The same day, Bullseye was released and it broke our installer. It won't fully work without tuning things as Ed mentioned above.

We're close of releasing a working installer for Raspbian OS Bullseye. Release is in testing. We just extended our team by 33% (1 new member 😊😊) that also helps with testing.

I hope Santa will bring the release even a bit late than Christmas but still this year...

Happy holidays!

**Comment by cyberluke** [comment]
Ok, gotcha. I work as java developer, but have Python experience (3 years) and Linux. I will build it and test it after Christmas. I remember for cases like this, we have used Python virtual environment and defined specific custom versions for everything. Another option would be docker, but that might bring some unnecesary overhead and perhaps drain battery more as well.

I see BLE is in the works, iOS for my daddy is my priority now. I will think of some additional ideas during the holidays. Hit me up if you need to help with something specific. I can dedicate 4 hours per week, sometimes more, sometimes less.

**Comment by wormstein** [comment]
Great, thanks.
No need for environment as the Mods will be the only thing running on RPi. There is a script in the project to setup an environment for developers who need to isolate this project. We keep track of python modules for n requirements.txt.

Currently were on hold over holidays on adding new features but anyone is free to work on their forks and send pull requests to the d v branch. 

I am now fixing the alpha release for bullseye.

There are small things to be worked on. Have a look at our Projects board. Although not all of our ideas are there you can see the major Projects. Everyone of those can be improved because we're still missing things.
The only way to see any possible improvements is to get a release installed and test it. Of course, new release is still wip.

Anyway, i think the best option for developers is to manual install the Mods. This means clonning the repo, setting the services, install python modules from requirements.txt and other small tunes. Then you can just update the local repo or test branches, etc

We can offer support on our Discord server. https://discord.gg/WY9XNNnSs6
