### ISSUE TITLE
Console is tty1 now on Bullseye

### ISSUE THREAD

**Issue by wormstein** [EdNekebno/DGTCentaur#96]
This needs to be changed in card-setup-tool 

`((Get-Content -path $CMDLINEFILE -Raw) -replace 'console=serial0,115200 ', '') | Set-Content -Path $CMDLINEFILE
`

**Comment by marcb1309** [comment]
Both Buster and Bullseye come with a default cmdline.txt that looks like:

Buster:
**console=serial0,115200 console=tty1** root=PARTUUID=738a4d67-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet init=/usr/lib/raspi-config/init_resize.sh

Bullseye:
**console=serial0,115200 console=tty1** root=PARTUUID=ae083906-02 rootfstype=ext4 fsck.repair=yes rootwait quiet init=/usr/lib/raspi-config/init_resize.sh splash plymouth.ignore-serial-consoles

For simplicity should we could remove a regex like "console=[a-za-Z]*[0-9](,[0-9]*)? " to catch both.

**Comment by wormstein** [comment]
This issue is invalid. Looks like serial0 needs to be removed. No changes needed.
