### ISSUE TITLE
postinst script - hostname not updated in /etc/hosts - postinst script refers to non existing file/etc/host

### ISSUE THREAD

**Issue by marcb1309** [EdNekebno/DGTCentaur#97]
Warning when running postinst script

sed: can't read /etc/host: No such file or directory

function update_hostname {
if [ ! $(hostname) = $HOSTNAME ]
then
    sed -i "s/$CURRHOSTNAME/$HOSTNAME/g" **/etc/host**
    sed -i "s/$CURRHOSTNAME/$HOSTNAME/g" /etc/hostname
fi
}

**Comment by wormstein** [comment]
Fixed on https://github.com/EdNekebno/DGTCentaur/commit/0bbe88aa565a85fd5cd464c03bbd7f7d220c81d3. CLosing.
