### ISSUE TITLE
Change default raspberrypi hostname does not work in build branch postinst script

### ISSUE THREAD

**Issue by marcb1309** [EdNekebno/DGTCentaur#99]
#### HARDWARE CONFIGURATION
DEFAULT_HOSTNAME="raspberrypi"
NEW_HOSTNAME="dgtcentaur"
function update_hostname {
#Do not update unless hostname is still the default one.
if [ ! $(hostname) = $DEFAULT_HOSTNAME ]
then
    sed -i "s/$DEFAULT_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
    sed -i "s/$DEFAULT_HOSTNAME/$NEW_HOSTNAME/g" /etc/hostname
fi
}
 update_hostname
cat /etc/hostname
cat /etc/hosts

I can´t see a change - it is still raspberry pi

change needed 

if [ ! $(hostname) = $DEFAULT_HOSTNAME ] -> if [ $(hostname) = $DEFAULT_HOSTNAME ]

**Comment by wormstein** [comment]
Fixed in commit https://github.com/EdNekebno/DGTCentaur/commit/21838c5e7733cc999baf6504fcee7499168ad1b6
Closing.
